# config/email_profiles.yaml

providers:
  gmail:
    domains:
      - gmail.com
    rules:
      - strip_extra_at
      - strip_plus_as_tag
      - strip_dots
      - strip_hyphens
      - make_lowercase
      - strip_whitespace

  protonmail:
    domains:
      - protonmail.com
      - protonmail.ch
      - proton.me
      - pm.me
    rules:
      - strip_extra_at
      - strip_plus_as_tag
      - strip_underscore
      - make_lowercase
      - strip_whitespace
      - strip_hyphens
      - strip_dots

  yahoo:
    domains:
      - yahoo.com
      - yahoo.co.uk
      - yahoo.fr
      - ymail.com
    rules:
      - strip_extra_at
      - strip_plus_as_tag
      - strip_hyphen_as_tag
      - make_lowercase
      - strip_whitespace

  fastmail:
    domains:
      - 123mail.org
      - 150mail.com
      - 150ml.com
      - 16mail.com
      - 2-mail.com
      - 4email.net
      - 50mail.com
      - airpost.net
      - aliencamel.com
      - allmail.net
      - bestmail.us
      - cluemail.com
      - elitemail.org
      - emailcorner.net
      - emailengine.net
      - emailengine.org
      - emailgroups.net
      - emailplus.org
      - emailuser.net
      - eml.cc
      - f-m.fm
      - fast-email.com
      - fast-mail.org
      - fastem.com
      - fastemailer.com
      - fastemail.us
      - fastest.cc
      - fastimap.com
      - fastmail.ca
      - fastmail.cn
      - fastmail.co.uk
      - fastmail.com
      - fastmail.com.au
      - fastmail.de
      - fastmail.es
      - fastmail.fm
      - fastmail.fr
      - fastmail.im
      - fastmail.in
      - fastmail.jp
      - fastmail.mx
      - fastmail.net
      - fastmail.nl
      - fastmail.org
      - fastmail.se
      - fastmail.to
      - fastmail.tw
      - fastmail.uk
      - fastmail.us
      - fastmailbox.net
      - fastmessaging.com
      - fea.st
      - fmail.co.uk
      - fmailbox.com
      - fmgirl.com
      - fmguy.com
      - foobox.com
      - foobox.net
      - ftml.net
      - h-mail.us
      - hailmail.net
      - imap-mail.com
      - imap.cc
      - imapmail.org
      - immerbox.com
      - immermail.com
      - inoutbox.com
      - internet-e-mail.com
      - internet-mail.org
      - internetemails.net
      - internetmailing.net
      - jetemail.net
      - justemail.net
      - letterboxes.org
      - lifetimeaddress.com
      - mail-central.com
      - mail-page.com
      - mailas.com
      - mailbolt.com
      - mailc.net
      - mailcan.com
      - mailforce.net
      - mailhaven.com
      - mailingaddress.org
      - mailite.com
      - mailmight.com
      - mailnew.com
      - mailsent.net
      - mailservice.ms
      - mailup.net
      - mailworks.org
      - mailzone.com
      - ml1.net
      - mm.st
      - myfastmail.com
      - mymacmail.com
      - nospammail.net
      - onepost.net
      - ownmail.net
      - penguinmail.com
      - permanentmail.com
      - petml.com
      - pobox.com
      - postinbox.com
      - postpro.net
      - proinbox.com
      - promessage.com
      - realemail.net
      - reallyfast.biz
      - reallyfast.info
      - rushpost.com
      - sent.as
      - sent.at
      - sent.com
      - siemprebox.com
      - siempremail.com
      - speedpost.net
      - speedymail.org
      - ssl-mail.com
      - swift-mail.com
      - the-fastest.net
      - the-quickest.com
      - theinternetemail.com
      - veribox.net
      - veryfast.biz
      - veryspeedy.net
      - warpmail.net
      - xsmail.com
      - yepmail.net
      - your-mail.com
    rules:
      - strip_extra_at
      - strip_fastmail_subdomain
      - strip_plus_as_tag
      - make_lowercase
      - strip_whitespace

  generic:
    domains: []
    rules:
      - strip_extra_at
      - strip_plus_as_tag
      - make_lowercase
      - strip_whitespace